//
//  KSubstringNoRepeats.swift
//  LeetCodeChallenge
//
//  Created by Xiao Liang on 7/11/19.
//  Copyright © 2019 TrackVia, Inc. All rights reserved.
//

import Foundation

class KSubstringNoRepeats: Runnable {
    func runTests() {
        let solution = SolutionWindow()
        print(solution.numKLenSubstrNoRepeats("hhyysznbloijgnzzglnytseiwbhmdljopspukrpkofmviuibwndwntevfnzqhqrfnqhrycedavehlotjqyiyerpgdcseptvwxtaqtquxsmwjiwefclkxynahykyikgazkyzdmqznqsivmyvwptylwobogqqxfkeplpawixdunlatkguhapyxrwvmumggxsoysatjxzduvnrtmavrsyoeovjfdeowjeqixrxpacmsfrcxtnsgmtvgetllhyimenfwzkguurnaqhnhcqvswfxrlrobvbzsjvsokzwtilsdgxgviixmfvyrmchonskawablkobibyujjcxvacehzwtcjfynotowocgvtmkhdlcnlmmoyuynmsywagadozhfadrdrsfudrkfstwvdaouiebjhnmweekqgrypovwoxsxzjgikiknvoofpsuanfyctvgqmlygpzomkeunislwvuemoizluzopjjkovkshqtmnmhaxfwovxifmjnoggcwpcolfnxlpjpdxjnpoquivhqsrxiafitnakkabdykngkxbwmdwfjlvyqxmeycxxdhuctlfcnrlqauhcxsmpyhvchcbppatpuemeubsdlelrsveqzqjwwwwapemyyyfrnljfptlxcuuqvhxfqvoioituobevgnkyrnzzjpibkfcovtlfoqdfzdxpafldeonfgsrevfbbhefnpfcnwjszoawoxjskvmdddiowowujtstaqzphtwdybhewnebfklgjoqfpfjdgyxfujujcxyusnhamagcwqbizkiqhuqdgjpwvlfccxgclzlexlztvzfvprvvzeaxxwczrndvacoobtpqmydeqookndxolmgnjptkgkgamukaroauszfmjyghlvsicbgurkceuekejklknaytcduvufjwovdpmcgivtfsbwyfhnjeclikrjiyuymgztnvhutyzbusbzpftzwkkvtuqrzjpduwfxgvgbkheabibyjwmardoubddgeesapdyvapnqdaboqimogbzildsdakramyvgimxpspbenqzdcqynhrhtukjefgeoppyswbckoobvrvfnplqqtbfwkhqwbftwjryqppkygyzhtdidhayuafytmwxmcqyvnwxoftninfqrbhfllzkqjvlmigazdegotfiwvbknuqxjmkprrnftlsvxrtfawywrfegpoxamdjoezxzfbtnpackeefepgklwopxqucglqcpdsdhjrunrsnkiqmxrgmsailkjgcwlsjvcziompwrsedcfkqyxyqmdskmazlqqxxbcpxsohdfdrbifbqnwyxqsfgvgxffwttdkbvkrejbbzgdwischdjdbzovrcqsrqadveaqnutxenxaosdoykoieikehjqbgasvcovlwhmthiwjisrsulbonkoegnvangcmspbwcvlnvoafqkkqetxmfynqtibsdrbmgeakffolnveuidnhfvvhpdxlkjemeadokimxocogmcajmpchwlvezzcryjmxwqseduohnauwvkzjqotjnbfflsyxmqhzwtahgwafgkcqaxqlkjcvdmzhbnoshyfrivrpasjuaitqwjyordeewbwqvysedmitvheckhtjlouzidzlfgreeeuvkbqidnomtziuofilptqdfcjdyahfxvmouzzwtfsskndjhnjumadhsdgqeoppjpuipzhovaggmiwdecrwyhfozgnuhsbsfdryfxmextolmqwksqognkxarpqsuecyxoghkdjjdrpoxpssyolfbelgztdenxibkkdupsmjyfmghranomdotjndmhfsiaqxhvfimjrtwtkcaycvrpcphbipraflbltccinytylpyxbnckickfzhxtayrmolukalccqfgnyqzsysnolmwhbnfsntwduxiengxmyozzmuylaamutewurmxcjpleiqhbsejiqcjuzcmgxjbcqskosmgjcwhmlpzbqxkqbgkgciljupwwnpnymtshlmyfznivvuqpnogusiuaydtlepuetatvrlppprkwldksljtoiusfpdywzjwsyevcyuyrewumnvutcxpumeskohefhvyrkeksczqkrnuddzlkclcmydriqkvzyoqsinhvdnfuunowlluqmbrekjzotudocpxehbqutytmmvyjnfcazyayxftzccykwsqtlyygvvfvzwcxfrcozzhdysslgbiomfkvqvonnurjypckwdcfrncvoclwgwurgicivtpzbdceqdumvvlsajpsbxnwiuiduxvwujfqiqibjitishuntulnfdoslsiavdabdtffmzizvpnxljacepssecltufyzevjqsopfaqhiiiovofayelorqidgjuaakpjtmyjygjpvasvkdmeawrnosjlppaulhcjhswdgayxvnflfhvzeqindwfmgpewxgzphnuuwbhwutmgwlmmxjvkqomelrbxjgmifzvcsywfciwpayemgnflvnugaofblpiuyrumgshtmgskzunwfvzgslfrllhgtxdhiqeapyoyrrpqhbkkgmlxnbskdiphrqugzaewenaxrfsdptpxmrupmppqzooggapsvivfxgdpeqicxxlvktsbndlidiodponxodygwjudzlucasewaqrntogxftaeyrwgwvsvyoccrslpnxgcdxymeevpwlixxrgesfshuqvjvzonauzpwadqolstteuerzfulyasutadhnmbjtnitiabgdxszgpbvepnnshnmqmynplbywkdukoajgcgckjvfxsiwwlmxzjpyzcxgpgtcsaxvjfqgqouzcclcvzujcnhfkpzwflbqvfxmdsaeyhixzbdjofaowyilntzctjhoigzvelcxvfliyobxgkgxjmrwrozatnqgkyeegiaviwxpsjalruwrrtccjdnwbzalhirjfpyiyoxitbjezaxacziazrgbnmvyiyiltkvpqwjtzclifgzqrgrxpzsanonhcuorlvxzukrdtsczexqrcqtjoljpemqbdfpfbctsimbrnczfvocypunsbhhbamrxivrfxtspfdjrzqbgqqzyjenpzqqwvdoxqquemjvrejylksqgqkvhebhjhrbyaacarhrciojkwbgdyycwsxgvijqcbqcyltyugycswrqespbkrlqhiedrhhzrstpmkddtiycgkhrcmxbfceujpzqayxetthebapophayaeydnhqykdjlauulcgdxkqjannbhcmzbzufvlyatvgwgzsipjudiibwlyhbfauusqsnojnvqivdfnrvljaciwriyzfspqywzfbsuwxwpkvofhgfrtgwuvumcvlnmdaabgcqqwzscojcwbppswioehacamnkjrofioxxfbxwbsiuixjniglxehlzlowhgqaiunivsohvutqwjsbiwbkdzupdnsmacgzemibeeqazsrenprdjaoklnukndopsgbbsyfcyazqabgtopybnzzffzjmwdscrdtovbaoswgezzzxnjzxjesptwmbvbrtqevvcoyjfpokmweencpdetxydumbtdokjjwbfdngtujebocmyhfjaeswpynbxobfbdktjiopjpdpfmbjohdnnzjycxduwoknuahqwqeuzqbaiknsjpufvwanyybebuumgyicglfdmokvhmvmvfdfayrpquoszbsorlehmzdgqfihrycjiqybfjsyxkxmfsqknvueacwwwarpjwywspqdpjzglbidasiqoroviadiaaefembwxxhlptghnvlwirkqedqivzfiwqyodzocfnpmdlogcxrkuspjzozrwbomwkylertcktgiqwjbmabjaborvtknwtwmkzcndchokuqjyblezygnnkzusuxtchxgyrkpmuekvzvieuxypgckvkwvkceoflutokpxdlgtbhuoynuhiynhfjjwgvkoioeessmxnsazahycbjwvpamqxqxtqxuqpjjdiedspnpyvtbcsethdeqlxqlvtzhnfwzpwsnricvrkyhyexlfeqflkfdavedboyrfwwxronqqghfycxnfvzxiifnczcgpddiephsniothkdojzdeyvjxmfhsafefuvcispyhrkkwpolldsuyuohejrhbavfhkitfppppwhbaelzmveczxrccsolgcrwbwdvtjbyhwttbaekfveiuymraixxnmmuxnedxpgbogfmbilkpelmufalxgaziyrojvrrofodoldajeuzhtwsvirmlitrchsghdxvgjjzlhrwpwblbgwozqkxkfdkyibpuirwdyhjpuycswukwgymclplrqreuvpkrmueealrnotajffxmqgrjzcxvrycmujshytaejupojdgloekdpndnevkcdqxfbvqrjvfjmembihonsgivvikcfaxxfgioajgrmdspvlrbipayjeuozwmkorybnbfxgnvxyowaiawrkfxgkkkyunqmlukaqmmkbkwnjbffuepigejbyndvksszfyaaldvlrwaqrukbljlptjabhphpyrvjeviemmolboinbqvktyuiupqgjzoatjgaykcpeypnfapdsfsycotkykpggrxtxzacixptocabcznmhcnqnrxshnyjgwdenweyemfmypyluvxyhpqqgqqwzolygmcaolojmcvfxglshwgfczcstbruyumhzvcigmpfdlohkvdyyaudywvxdpzhfvjmjfpiknlklwovzawfjrfigjlqcizwiamklmocpdaocuwjtgurcberrsgvyzgwvwrjwwavhusoqvudviqadonkukykwiltzkfnxjpatwqzupwmetmyoobggisgahjzjjuaipvtweyfiyafynqpkdjixrkjmysprqiwzoirroiseeehirepmzzkykuqbllsqcelogvvkdqzvtpubhkyeemvmouonsxqtmhumkhrxpwnlhxwdrwcevemvoeeqltpjjvzdeovcgbclwpszendyextastrxmbabuhufhiakpycdqapwgrkgaqmgpnaehcchozyplelvgtczwdlstcvnjwqrhandpktqdbznjcozjvarxzmyghubcxnajswrkjksikxvjkibxhmzzcpdmdcupmmufdvghzeavqvmotksxjpkdftpqiwzpiexujckqzdhhccitdilggegarmptzmqlsfkmpdlkpdpedtnsdcnzwfcofxkxuqhltecexkfvmrlbjfszldamiukcwhpcdezzopnuvwpsccmfomtgiwfanakaqkozvxkzvratlngqfqvjjwyjzdujsffcmwuocsqrfpqcdlirgyggqdrmuwwszglyvoehmdmtrhpgskhvfdehtnjbsiqubnsgyzojxssrwdwuyvzilrghifcppyclyukmsnbkzeugjmwxllqaygsjrzuzdzgqggmqxfclayrbkpyghqhddhvqmdolmvurpbmckuzykovsawsekhftdvkzoquoemssnqgqqkltssowuutcqosmmcpjxnlnctbqrqhuqpjlqwrzjkwsqnwgjvjadkfashaixnxuxstoofwkawxtwltgltlfolwqhpsjfdgpeaqigkbnkmhhirlzhifukocpqvrohqftghhwzlefhdrjnfupscqgsirnyvkqddizptyldccmeulzirrpnebfiaueimgiwntnatslkgpuedcgjuvhcfsaigrpwgovoixgeuamuztzxircvkydudmfexbadycipmyazfwrpttznakoaluskuivgtugunggxjeaaybaozjqzkigcklqxltqsianejumqimbupmvsszydfsxauumclaxrnemezikugsfuhijjiedsdbkqhjqrlpnfaqrgtdjabuyvfmyihqpxmzgjdaslxadesuxjcctisyieaofhunkoijowtaijjcevbwikavdopcbaagolkqwgncvivnmiouqndzegsztteirvzpeypfubtgkifjutrfrobfvizioegiocgejtrsepzgzcaiufejaztmmmvlznllduycktbwhxbnjvtvfsgtjqwfffpdjzosrizuyrfzvospgbqdptcyizzszyrdrqlqyxbkamzpnqxtzihjthhkyfyvosnssoyebdfspuibvqseumppbfimjsjfhommbwerxhcxcexkwfneguiwqwebopaiokhplkugcwavagqxjwfibqbnmqgodngahxjibrgqbpskwgdzicrxmhoogwlhhuawmhswgiigcrdmveijtijppglbpvfnouyavswanjzmvydetsaoymavhipvlgihnisqckzhiypqqdotxdodzbjufqdtfuuhfolehbxnswnbdvzmlbwqguiywmzisxmxrardmimvjdzlytlvceothetslpzzekxocsknbhruyprhxiijeqxqhobnjnwblsusbqlybvaezmwpswtpmdpxfehgdqkvdcmzloplbrswledrxgfvikcvfvvrazxlwzobsxaixeclkvgjglyuvlawsuqdfwihlndksbqeawclagjzxmwpnqxekmvlskaofjaiuowjsipmwfneosskjldqokohcydwujfgyaqfoajfsqwrxhzcmcvqclrwlypidbtpslliegywkhaiesbgdbxtbnbougtajjddzckulsckjkohgdowjhrtxrjezfncilxhfjaktjrfimjglabxxqzeggpktnfdtcxvxiwoezblxtxtaljcoguhmckimwbvamakqvlbeqjfnbeleazwcptchllwoqfuzaznliulrzwywonopglxodujzqmrgxncctxusassxbjatmwzevjvenkicztmgnnbodcirtezacgypvtesaccnpdpodfqqwpcfxokrkeskatxhknttktjkxlfvtnxpllgenqpjabpndsjrlxtnyvsrztxjnbmwcdxjtbsfygutaulmifekdavflrsuypmzjzzsynjvneorioqnfnkypsxswqujqshgdoeszukqfxjpdrldwgbsvsjswrduvzdshcynmhgzzdrevfvamqvjgdquhyvqiipbjtqwinofjefavugqhuhbgxjxtdcjospriywjquvqpavcrewclvsteoqqcesebszvcymgtrknmgtialwsgsgsodgybydregtvuvptafpwgmahxltsaejgrppqjhulyvhouphlmmjscrcegnoaicrwhuafcbphalgejwoohkqfjdhlcsmqwnqmshwauoqtdmcaifdtgupgicmwkqzlwcxkfbrsxsulswrktpptkfxhelrtxdfbwstziyayqtpdvpqlesrowzqglogeosteybznyiijnexlhhgmsaluttqkkwnhbmzjlwrlbswldznhvbjutkwxlkbijwpctylshzsdhpcxwmvhyeuiysolzojxyasnwwpqugfvlvvxccrefmehaiqufzzixqwyscmbaaanjjurqngvixtigewczkezsakawrfunanfoajqnryaoxkgxocbpwjwoxkozqrndujficdutcdsueqgzabtvlqujxfqfbireqammxntjqqyzyyyfpvcmmeybprrxktfrzaaxabglvfsooznnfyygeotmqahoqvkuxxadamaqtahstbdxwyislzdczqmzecrncpmdhnugvzzyfshpaaonrjdqjxctgvhphbagxdvconmqsrfbmxjvjczglgcnlbjmxepvtykzrakirxmcvshvkioepnkrwcsmexbtigyzrstudfkilldkwxuajhbujxhjoaddfzkwpyvbhmhlhdfbjmkouarvlzevknamykhbdyevnuirzpntgarflmipkcriokqgxfdakmyltolybzbrynabgouhavxgcobifahrannkebqtaztycewabwahhhgsbsdtzkfibzplddysapdqoncmmkeutlqmefwdosoxqwsfkicdcrniwnrjietbsejavrqtixcgnzomwxgoaondpdoaexhdnqgoqipphfojfsblzwczoelnqgimsbkpnhlyainncztbohksjzbjzkbbyrszcewfekivzigiwaiwywlncetaowbdzizynrsasaoxaophtgsktodegtampgtazrjqtsqjewissyrqdoovxofengrhyhxowvdvgjbllclyjhunlbfbvnjrujunyfmdhcnwolqfgbmrfrtyucijaxktouqgbgmkrsuiletyjyqeyuoyarqtdybgkznhesadtzajpmaiwnovpjsysswzysooiwxopodaaamrkofoetnrcqjgtgpnowxymlbjikxaoytqomwrkfgvbnwujnogsrgozpjwiqvilekgzmniomvcrxvkkxkenmnjvstfctkaxguyxgwajqranuofrczmsdisvwixgxwsdjaomzrlzkogocduffszayfcssfacipbaybqftimfqnoxxavinxdshdsctzyrntdnrikskgiifwckprmfxnszibuurtxlgoexdctjhiokswajbeubxslcgdxkvfphlgistkhzogjdladygnzgcrsxpwdqmdefxrqidbntyfeimtljgcsadhlnrrwzbafnagsrqvidjerwznlzhhamxzqalsecfymowcfktyxzlnhdmqbifxrzaatapahuivpazbeiqtleulbkbjrzhcqlodwqstgwiyxcaqyccmgguulzopwmvtqajfaritlzohxhxrnwwevhwcmxjxdnrskztrtpnuimlpxbuxceqiqeyxwfesknuwlhmutaqgnwutsmqwbjvalcvnmvxwiikfehgdrhhztvyyqalvwcytsbpmipwpqtpexladcemnksxgjwzqfywfgtyoymlwkdlwtdewsjxsdguzczdrsrtlnzrvbtjulzpjsgyxmzsitbogvxdaspsgzrkblgoqtsjvgdnachgvzjfunstrptelmunsxqqgpnfwlfuuufahalxihcqyqcjraaakdqglxomwcqwlkvfcygvdqwcfqkulytuvnsfsjrglegcabsdsgpxzlvvoevegjuvisgygcahnaqyfrwsuqafssxqflyxmxojzsbbnmvyvhbiyevsgobfjwadmhsysjdzzwcmbdyraebpoakqrahnzjbgtdzyqczncmxbdzroegcqklwlahejxrdqxuovritprphhuopqkhdsfcxadzbhnuoporoyvohgiybkdwadbyregzlxvenjwfundpzszfpabjrjlnedpwkuuktivoutumxkqunyrpafuldeuguhzyhzgpfztztvloguazpsuybiaryuupidbvflqiitdmazgsqgdfypmainuetqiogpxpabalsabvqfpnzvlzogmzxgjbgcjsscphggpqrmbbqaywrjmcmfnehdujpzskygdmayzyogbvgzwphqbubqqpavhsfihuojhtbdrdeirmeggjsahozykakayzrevzjjphnprpzctrnkboyxalgxudywxjgvshphxjrkytrflxmxootsssxvfvnchxusxlyjhlkcsdhxcsvarslwoalalcfonkhwgrsbfompuwvyqhpiawrunnkkktabzswfmeoanptlzyahqfnyongsbsnvflbxwukegdnizwoeklmquavpvqewuqxpahauinsavghxnzsgpddxfqhtlvpcessybiowrcctevdsyxfzqfwsfkgsdoifuvqpbcejomymumrhughjlfyisurrbwxyimgoocoybcfymxrmyxrfwgbzivgjoxiyashzxwmhfmxplbqyedidmqpxtkupjrglndtjriozqrdwcyebtezhynvfhblohsadnemppvdeouegxkipfbigvehjqrjueekmdspxhffgjkwtzgpamadrmxxlwvqhkbgfjpbivhmynaeewinfahcwwyykdogsq", 10000))
    }
    
    private class SolutionWindow {
        func numKLenSubstrNoRepeats(_ S: String, _ K: Int) -> Int {
            if K > S.count { return 0 }
            let chars = Array<Character>(S)
            var count = 0
            
            var window = createWindow(chars, 0, K)
            if !hasRepeat(window) {
                count += 1
            }
            
            if chars.count > K {
                for i in 1...(chars.count - K) {
                    window[offset(chars[i - 1])] -= 1
                    window[offset(chars[i + K - 1])] += 1
                    
                    if !hasRepeat(window) {
                        count += 1
                    }
                }
            }
            
            return count
        }
        
        private func createWindow(_ chars: [Character],
                          _ start: Int,
                          _ K: Int) -> [Int] {
            var window = [Int](repeating: 0, count: 26)
            for i in start..<K {
                let c = chars[i]
                window[offset(c)] += 1
            }
            return window
        }
        
        private func offset(_ character: Character) -> Int {
            return Int(character.asciiValue!) - Int(Character("a").asciiValue!)
        }
        
        private func hasRepeat(_ window: [Int]) -> Bool {
            for i in 0..<26 { if window[i] > 1 { return true } }
            return false
        }
    }
}
